# Generated by Django 5.1.4 on 2024-12-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_post_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
